language: php

sudo: false

cache:
 apt: true
 directories:
    - $HOME/.composer/cache/files

php:
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install --no-interaction

script:
  - find src tests/php \( -name '*.php' \) -exec php -l {} \;
  - vendor/bin/phpunit
